### PR TITLE
Update ansible playbook

### PR DESCRIPTION
**Pull request by egeakman**
- Update server IP address
- Since the repo is public, we don't need ssh cloning. Use https instead.
- When I first tried, it threw an error about group 1000 not existing. Added this step to ensure it exists.
- The renaming was not necessary, just wanted to match the actual server host name

### CODE REVIEW

**Comment by NMertsch** [comment]
Thank you @egeakman. I don't know ansible, so I'm currently guessing what these changes mean. A PR description would be nice :)

Can you confirm my guesses?

- Update bot server IP address
- Clone git repo via HTTPS instead of SSH, don't require SSH key file for cloning
- Ensure the `bot` group exists
- Rename bot server configuration from `bot_server` to `discord2024` (why?)

**Comment by egeakman** [comment]
Hi, sorry! I was in a hurry and forgot to add one.

**Review by NMertsch — CHANGES_REQUESTED** [review]
That's okay :)

Assuming I understood the changes correctly, I agree with the first three points, but disagree with renaming `bot_server` to `discord2024`:

- I find `bot_server` easier to understand. It is the IP address of the server where we host the bot.
- It is not the IP address of a discord server.
- Next year, `2024` would need to be changed to `2025`.

Would it be okay to revert that name?

**Comment by egeakman** [comment]
> That's okay :)
> 
> Assuming I understood the changes correctly, I agree with the first three points, but disagree with renaming `bot_server` to `discord2024`:
> 
> * I find `bot_server` easier to understand. It is the IP address of the server where we host the bot.
> * It is not the IP address of a discord server.
> * Next year, `2024` would need to be changed to `2025`.
> 
> Would it be okay to revert that name?

Of course! What you said makes sense to me, let's revert it.

**Review by NMertsch — APPROVED** [review]

**Pull request merged**
